# Generated by Django 3.2.7 on 2023-02-11 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Assigned to Reporter', 'Assigned To Reporter'), ('Assigned to Manager', 'Assigned To Manager'), ('Assigned to Troubleshooter', 'Assigned To Troubleshooter'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Assigned to Quality Checker', 'Assigned To Quality Checker'), ('Completed', 'Completed')], max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('var_changed', models.CharField(max_length=64)),
                ('prev_state', models.CharField(max_length=64, null=True)),
                ('current_state', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=5000)),
                ('action_type', models.CharField(max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cretby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
