# Generated by Django 3.2.7 on 2023-03-29 09:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230320_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainer',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=15),
        ),
        migrations.CreateModel(
            name='FactoryDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=50)),
                ('SubDepartment', models.CharField(max_length=50)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.factory')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastModified', models.DateTimeField(blank=True, default=django.utils.timezone.localtime)),
                ('createdBy', models.CharField(max_length=100)),
                ('Languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('templateTitle', models.CharField(max_length=100)),
                ('sendCount', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('MODIFIED', 'Modified')], default='Sent', max_length=15)),
                ('Genders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None)),
                ('templateIDs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None)),
                ('departments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None)),
                ('messageBody', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(max_length=1000), default=list, size=None)),
                ('inputVariables', models.JSONField(default=None, null=True)),
                ('Factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.factory')),
            ],
        ),
    ]
