# Generated by Django 3.2.7 on 2023-03-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230329_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='SenderID',
            field=models.CharField(default='INACHE', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='PhoneNo',
            field=models.CharField(max_length=15),
        ),
    ]
