# Generated by Django 3.2.7 on 2023-04-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230330_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoftDeleteModel',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='uuid',
        ),
    ]
