# Generated by Django 3.2.7 on 2023-04-26 06:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230409_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='CurrentStatus',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Read', 'Read'), ('Unread', 'Unread'), ('new_cases', 'New Case'), ('Submit', 'Submit')], default='new_cases', max_length=20),
        ),
        migrations.AddField(
            model_name='complainer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Modified', 'Modified'), ('CTDraft', 'Ctdraft')], default='Sent', max_length=15),
        ),
        migrations.AlterField(
            model_name='casereslovingreport',
            name='CCRWhathappened',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='casereslovingreport',
            name='CCRWhen',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='casereslovingreport',
            name='CCRWhere',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='smstemplates',
            name='user_roles_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
    ]
