# Generated by Django 3.2.7 on 2023-04-30 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0003_tokenproxy'),
        ('accounts', '0008_auto_20230426_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemanager',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='casemanager',
            name='Factory',
        ),
        migrations.RemoveField(
            model_name='casemanager',
            name='baseusermodel_ptr',
        ),
        migrations.RemoveField(
            model_name='casereporter',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='casereporter',
            name='Factory',
        ),
        migrations.RemoveField(
            model_name='casereporter',
            name='baseusermodel_ptr',
        ),
        migrations.RemoveField(
            model_name='casesettings',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='casetroubleshooter',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='casetroubleshooter',
            name='Factory',
        ),
        migrations.RemoveField(
            model_name='casetroubleshooter',
            name='baseusermodel_ptr',
        ),
        migrations.RemoveField(
            model_name='factoryadmin',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='factoryadmin',
            name='Factory',
        ),
        migrations.RemoveField(
            model_name='factoryadmin',
            name='baseusermodel_ptr',
        ),
        migrations.AlterField(
            model_name='case',
            name='CaseManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_m', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='CaseReporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_r', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='CaseTroubleShooter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_t', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BrodcastMessage',
        ),
        migrations.DeleteModel(
            name='CaseManager',
        ),
        migrations.DeleteModel(
            name='CaseReporter',
        ),
        migrations.DeleteModel(
            name='CaseSettings',
        ),
        migrations.DeleteModel(
            name='CaseTroubleShooter',
        ),
        migrations.DeleteModel(
            name='FactoryAdmin',
        ),
    ]
