# Generated by Django 3.2.7 on 2023-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230430_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('Assigned to Reporter', 'Assigned To Reporter'), ('Assigned to Manager', 'Assigned To Manager'), ('Assigned to Troubleshooter', 'Assigned To Troubleshooter'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Re Investigation', 'Re Investigation'), ('Closed', 'Closed'), ('Assigned to Quality Checker', 'Assigned To Quality Checker'), ('Completed', 'Completed')], max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='CaseStatus',
            field=models.CharField(choices=[('Assigned to Reporter', 'Assigned To Reporter'), ('Assigned to Manager', 'Assigned To Manager'), ('Assigned to Troubleshooter', 'Assigned To Troubleshooter'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Re Investigation', 'Re Investigation'), ('Closed', 'Closed'), ('Assigned to Quality Checker', 'Assigned To Quality Checker'), ('Completed', 'Completed')], default='Assigned to Reporter', max_length=64),
        ),
    ]
