# Generated by Django 3.2.7 on 2023-05-11 09:37

import accounts.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230501_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('programName', models.CharField(max_length=30)),
                ('programDuration', models.IntegerField()),
                ('participants', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('uploadedAt', models.DateTimeField(blank=True, default=django.utils.timezone.localtime)),
                ('Agenda', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=1000)),
                ('programStatus', models.JSONField(default=None, null=True)),
                ('Reason', models.CharField(blank=True, max_length=1000)),
                ('Breached', models.BooleanField(default=False)),
                ('uploadedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='factory',
            name='requiredAwarenessProgram',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='ProgramAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attachement', models.FileField(upload_to=accounts.models.program_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('awarenessProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.awarenessprogram')),
            ],
        ),
        migrations.AddField(
            model_name='awarenessprogram',
            name='Factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.factory'),
        ),
    ]
