# Generated by Django 3.2.7 on 2023-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230511_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='CaseCategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='CaseDetails',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='CaseValidation',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Priority',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='SubCategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
