# Generated by Django 3.2.7 on 2023-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230516_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='Number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
