# Generated by Django 3.2.7 on 2023-05-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_factory_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseusermodel',
            options={'permissions': (('view_awareness_program', 'view awareness program'), ('add_awareness_program', 'add awareness program'), ('change_awareness_program', 'change awareness program'), ('view_broadcast_message', 'view broadcast message'), ('add_broadcast_message', 'add broadcast message'), ('change_broadcast_message', 'change broadcast message'), ('view_holiday_calendar', 'view holiday calendar'), ('add_holiday_calendar', 'add holiday calendar'), ('change_holiday_calendar', 'change holiday calendar'), ('delete_holiday_calendar', 'delete holiday calendar'), ('crud_factory_admin', 'crud factory admin'), ('crud_cr', 'crud case reporter'), ('crud_cm', 'crud case manager'), ('crud_ct', 'crud case troubleshooter'))},
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=30)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('Factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.factory')),
            ],
        ),
    ]
