# Generated by Django 3.2.7 on 2023-06-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20230531_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='CaseDescription',
        ),
        migrations.RemoveField(
            model_name='case',
            name='Tag',
        ),
        migrations.DeleteModel(
            name='FactoryNumber',
        ),
    ]
