# Generated by Django 3.2.7 on 2023-06-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230602_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseLogs',
        ),
    ]
