# Generated by Django 3.2.7 on 2023-06-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_caselogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereslovingreport',
            name='CCRvariables',
            field=models.JSONField(default=None, null=True),
        ),
    ]
