# Generated by Django 3.2.7 on 2023-07-03 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_casereslovingreport_ccrvariables'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile_S3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='case',
            name='CaseFileupload',
        ),
        migrations.CreateModel(
            name='User_Profilepic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.uploadedfile_s3')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedfile_s3',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awarenessprogram',
            name='Files',
            field=models.ManyToManyField(blank=True, to='accounts.UploadedFile_S3'),
        ),
        migrations.AddField(
            model_name='case',
            name='File',
            field=models.ManyToManyField(blank=True, to='accounts.UploadedFile_S3'),
        ),
    ]
