# Generated by Django 3.2.7 on 2023-07-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20230704_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Information', models.JSONField()),
                ('type', models.CharField(choices=[('Send Message', 'Send Message')], default='Send Message', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('Assigned to Reporter', 'Assigned To Reporter'), ('Reassigned to Reporter', 'Reassigned To Reporter'), ('Assigned to Manager', 'Assigned To Manager'), ('Reassigned to Manager', 'Reassigned To Manager'), ('Assigned to Troubleshooter', 'Assigned To Troubleshooter'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Re Investigation', 'Re Investigation'), ('Closed', 'Closed'), ('Assigned to Quality Checker', 'Assigned To Quality Checker'), ('Completed', 'Completed'), ('Unreponsive', 'Unresponsive')], max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='CaseStatus',
            field=models.CharField(choices=[('Assigned to Reporter', 'Assigned To Reporter'), ('Reassigned to Reporter', 'Reassigned To Reporter'), ('Assigned to Manager', 'Assigned To Manager'), ('Reassigned to Manager', 'Reassigned To Manager'), ('Assigned to Troubleshooter', 'Assigned To Troubleshooter'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Re Investigation', 'Re Investigation'), ('Closed', 'Closed'), ('Assigned to Quality Checker', 'Assigned To Quality Checker'), ('Completed', 'Completed'), ('Unreponsive', 'Unresponsive')], default='Assigned to Reporter', max_length=64),
        ),
        migrations.CreateModel(
            name='Incentives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRsendDate', models.DateTimeField(blank=True, null=True)),
                ('CRreceiveDate', models.DateTimeField(blank=True, null=True)),
                ('CMsendDate', models.DateTimeField(blank=True, null=True)),
                ('CMreceiveDate', models.DateTimeField(blank=True, null=True)),
                ('CTsendDate', models.DateTimeField(blank=True, null=True)),
                ('CTreceiveDate', models.DateTimeField(blank=True, null=True)),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.case')),
            ],
        ),
    ]
