# Generated by Django 3.2.7 on 2023-08-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20230804_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cretbyal', to='accounts.userrolefactory'),
        ),
        migrations.AlterField(
            model_name='uploadedfile_s3',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userrolefactory'),
        ),
    ]
