# Generated by Django 3.2.7 on 2023-08-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_baseusermodel_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='RegionalAdmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_a', to='accounts.userrolefactory'),
        ),
        migrations.AddField(
            model_name='casereslovingreport',
            name='CCRComments_RA',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('Assigned to Reporter', 'Assigned To Reporter'), ('Assigned to Manager', 'Assigned To Manager'), ('Assigned to Troubleshooter', 'Assigned To Troubleshooter'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Re Investigation', 'Re Investigation'), ('Closed', 'Closed'), ('Assigned to Quality Checker', 'Assigned To Quality Checker'), ('Completed', 'Completed'), ('Unreponsive', 'Unresponsive'), ('Approved', 'Approved'), ('Assigned to Regional Admin', 'Assigned To Regional Admin'), ('Investigation under Regional Admin', 'Ra Investigation'), ('Regional Admin ReInvestigation', 'Re Investigation Ra')], max_length=64),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='role',
            field=models.CharField(choices=[('CR', 'Case Reporter'), ('CM', 'Case Manager'), ('CT', 'Case Troubleshooter'), ('FACTORY_ADMIN', 'Factory Admin'), ('SUPER_ADMIN', 'Super Admin'), ('INACHE_ADMIN', 'Inache Admin'), ('REGIONAL_ADMIN', 'Regional Admin'), ('DEFAULT_ROLE', 'Default Role')], default='DEFAULT_ROLE', max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='CaseStatus',
            field=models.CharField(choices=[('Assigned to Reporter', 'Assigned To Reporter'), ('Assigned to Manager', 'Assigned To Manager'), ('Assigned to Troubleshooter', 'Assigned To Troubleshooter'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Re Investigation', 'Re Investigation'), ('Closed', 'Closed'), ('Assigned to Quality Checker', 'Assigned To Quality Checker'), ('Completed', 'Completed'), ('Unreponsive', 'Unresponsive'), ('Approved', 'Approved'), ('Assigned to Regional Admin', 'Assigned To Regional Admin'), ('Investigation under Regional Admin', 'Ra Investigation'), ('Regional Admin ReInvestigation', 'Re Investigation Ra')], default='Assigned to Reporter', max_length=64),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('CR', 'Case Reporter'), ('CM', 'Case Manager'), ('CT', 'Case Troubleshooter'), ('FACTORY_ADMIN', 'Factory Admin'), ('SUPER_ADMIN', 'Super Admin'), ('INACHE_ADMIN', 'Inache Admin'), ('REGIONAL_ADMIN', 'Regional Admin'), ('DEFAULT_ROLE', 'Default Role')], default='DEFAULT_ROLE', max_length=64, unique=True),
        ),
    ]
