# Generated by Django 3.2.7 on 2023-09-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_case_casenature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseusermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=20, null=True),
        ),
    ]
