# Generated by Django 3.2.7 on 2023-09-11 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_baseusermodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolefactory',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
