# Generated by Django 3.2.7 on 2023-09-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userrolefactory_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('Assigned to Reporter', 'Assigned To Reporter'), ('Assigned to Manager', 'Assigned To Manager'), ('Assigned to Troubleshooter', 'Assigned To Troubleshooter'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Re Investigation', 'Re Investigation'), ('Closed', 'Closed'), ('Assigned to Quality Checker', 'Assigned To Quality Checker'), ('Completed', 'Completed'), ('Unresponsive', 'Unresponsive'), ('Approved', 'Approved'), ('Assigned to Regional Admin', 'Assigned To Regional Admin'), ('Investigation under Regional Admin', 'Ra Investigation'), ('Regional Admin ReInvestigation', 'Re Investigation Ra')], max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='CaseStatus',
            field=models.CharField(choices=[('Assigned to Reporter', 'Assigned To Reporter'), ('Assigned to Manager', 'Assigned To Manager'), ('Assigned to Troubleshooter', 'Assigned To Troubleshooter'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Re Investigation', 'Re Investigation'), ('Closed', 'Closed'), ('Assigned to Quality Checker', 'Assigned To Quality Checker'), ('Completed', 'Completed'), ('Unresponsive', 'Unresponsive'), ('Approved', 'Approved'), ('Assigned to Regional Admin', 'Assigned To Regional Admin'), ('Investigation under Regional Admin', 'Ra Investigation'), ('Regional Admin ReInvestigation', 'Re Investigation Ra')], default='Assigned to Reporter', max_length=64),
        ),
    ]
