# Generated by Django 3.2.7 on 2023-11-14 11:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20230926_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='Departments',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='factories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='Factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.factory'),
        ),
    ]
