# Generated by Django 3.2.7 on 2023-11-14 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20231114_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='departments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, null=True, size=None),
        ),
    ]
