# Generated by Django 3.2.7 on 2023-12-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_incentivepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_to_be_triggered', models.CharField(max_length=50)),
                ('notification_rules', models.JSONField(default=None, null=True)),
                ('schedule', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('event_identifier_items', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.case'),
        ),
        migrations.CreateModel(
            name='SNSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('subject', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('variables', models.JSONField(default=None, null=True)),
                ('template_category', models.CharField(max_length=255)),
                ('company_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_subject', models.CharField(max_length=1000)),
                ('message_content', models.CharField(max_length=10000)),
                ('sns_topic_name', models.CharField(max_length=1000)),
                ('notification_type', models.CharField(max_length=255)),
                ('log', models.JSONField(default=None, null=True)),
                ('event_identifier', models.JSONField(blank=True, null=True)),
                ('notification_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.notification')),
                ('template_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.snstemplate')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='template_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.snstemplate'),
        ),
    ]
