# Generated by Django 3.2.7 on 2024-01-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_userrolefactory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolefactory',
            name='last_login_role',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
