# Generated by Django 3.2.7 on 2024-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_userrolefactory_last_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolefactory',
            name='IsUnsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
