# Generated by Django 3.2.7 on 2024-01-11 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_userrolefactory_isunsubscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolefactory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
